total node: 8
node keys: 
5 
node keys: 
2 
node keys: 
1 
node keys: 
3 4 
node keys: 
8 21 
node keys: 
6 
node keys: 
20 
node keys: 
22 80 

total node: 7
node keys: 
5 
node keys: 
2 
node keys: 
1 
node keys: 
3 4 
node keys: 
21 
node keys: 
8 20 
node keys: 
22 80 

total node: 7
node keys: 
5 
node keys: 
3 
node keys: 
1 
node keys: 
4 
node keys: 
21 
node keys: 
8 20 
node keys: 
22 80 

total node: 7
node keys: 
5 
node keys: 
3 
node keys: 
1 
node keys: 
4 
node keys: 
20 
node keys: 
8 
node keys: 
22 80 

total node: 7
node keys: 
5 
node keys: 
3 
node keys: 
1 
node keys: 
4 
node keys: 
22 
node keys: 
20 
node keys: 
80 

total node: 4
node keys: 
5 22 
node keys: 
1 3 
node keys: 
20 
node keys: 
80 

total node: 4
node keys: 
3 20 
node keys: 
1 
node keys: 
5 
node keys: 
80 
